## NumPy


*   It is Python Library.
*   NumPy is short for Numerical Python
*   It is used for working (computation & processing) with arrays( single & multidimensional array)

* Smaller memory consumption and better runtime behaviour.


To install the library

 --> pip install numpy

 import numpy


## Basic Operations

In [6]:
import numpy as np


In [7]:
a = np.array([1,2,3])

In [8]:
print(a)

[1 2 3]


In [10]:
type(a)

numpy.ndarray

In [11]:
a = np.array([1,2,3],dtype = float)
print(a)

[1. 2. 3.]


In [15]:
b = np.array([[1,2,3],[4,5,6]]) #2D array with 2 rows and 3 columns
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
type(b)

numpy.ndarray

In [17]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) #2D array with 3 rows and 3 columns
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
type(b)

numpy.ndarray

In [22]:
a.ndim    # .ndim to get dimensions of a numpy array

1

In [21]:
b.ndim

2

In [24]:
c = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(c)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [25]:
c.ndim

4

### **## Why use NumPy when we have list in Python?**



*   Lists are slow to process.
*   NumPy aims to provide an array object which is 50x faster than Python lists.
*   Numpy provides many supporting functions.

* Arrays are frequently used in datascience where speed and resources are very imp.

x-axis: 1,
y-axis: 0,
z-axis: 2

In [26]:
a

array([1., 2., 3.])

In [35]:
d = np.array([[9,4,3],[5,6,7]],dtype=float)

In [36]:
d

array([[9., 4., 3.],
       [5., 6., 7.]])

In [38]:
a.shape

(3,)

In [39]:
d.shape

(2, 3)

In [31]:
b.shape

(3, 3)

In [40]:
b.dtype

dtype('int64')

### Accessing/Changing specific elements, rows & columns etc.

In [42]:
a = np.array([[1,2,3,4,5,6,7,8],[8,7,6,5,4,3,2,1]])
print(a)

[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]]


In [43]:
a.ndim

2

In [45]:
print(a[0,3])

4


In [67]:
#Get a specific row from a numpy array
a[1,:]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [71]:
#Get a specific column froma numpy array
a[:,0]

array([1, 8])

In [50]:
a[1,2:]

array([6, 5, 4, 3, 2, 1])

In [51]:
a[1,2:5]

array([6, 5, 4])

In [52]:
a[0,5] = 70

In [57]:
print(a[0,:])    #mistake: missed comma

[ 1  2  3  4  5 70  7  8]


## Zeros/Ones method in NumPy

In [60]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [64]:
np.full((4,4),50)

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])