## NumPy


*   It is Python Library.
*   NumPy is short for Numerical Python
*   It is used for working (computation & processing) with arrays( single & multidimensional array)

* Smaller memory consumption and better runtime behaviour.


To install the library

 --> pip install numpy

 import numpy


## Basic Operations

In [4]:
import numpy as np


In [7]:
a = np.array([1,2,3])

In [8]:
print(a)

[1 2 3]


In [10]:
type(a)

numpy.ndarray

In [11]:
a = np.array([1,2,3],dtype = float)
print(a)

[1. 2. 3.]


In [15]:
b = np.array([[1,2,3],[4,5,6]]) #2D array with 2 rows and 3 columns
print(b)

[[1 2 3]
 [4 5 6]]


In [14]:
type(b)

numpy.ndarray

In [6]:
b = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[2,3,4],[5,2,3],[7,9,6]]]) #3D array with 3 rows and 3 columns
print(b)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[2 3 4]
  [5 2 3]
  [7 9 6]]]


In [18]:
type(b)

numpy.ndarray

In [22]:
a.ndim    # .ndim to get dimensions of a numpy array

1

In [21]:
b.ndim

2

In [24]:
c = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
print(c)

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]


In [25]:
c.ndim

4

### **## Why use NumPy when we have list in Python?**



*   Lists are slow to process.
*   NumPy aims to provide an array object which is 50x faster than Python lists.
*   Numpy provides many supporting functions.

* Arrays are frequently used in datascience where speed and resources are very imp.

x-axis: 1,
y-axis: 0,
z-axis: 2

In [26]:
a

array([1., 2., 3.])

In [35]:
d = np.array([[9,4,3],[5,6,7]],dtype=float)

In [36]:
d

array([[9., 4., 3.],
       [5., 6., 7.]])

In [38]:
a.shape

(3,)

In [39]:
d.shape

(2, 3)

In [31]:
b.shape

(3, 3)

In [40]:
b.dtype

dtype('int64')

### Accessing/Changing specific elements, rows & columns etc.

In [9]:
a = np.array([[1,2,3,4,5,6,7,8],[8,7,6,5,4,3,2,1]])
print(a)

[[1 2 3 4 5 6 7 8]
 [8 7 6 5 4 3 2 1]]


In [10]:
a.ndim

2

In [11]:
print(a[0,3])

4


In [34]:
#Get a 1st row all columns
a[1,:]

array([10, 20, 30, 40, 50, 60])

In [35]:
#Get all rows  5th column froma numpy array
a[:,5]

array([ 6, 60, 12, 61, 64])

In [14]:
a[1,2:]  #Get the 1st row starting from 2nd column

array([6, 5, 4, 3, 2, 1])

In [15]:
a[1,2:5] #Get the 1st row starting from 2nd coulmn and ending before 5th column

array([6, 5, 4])

In [52]:
a[0,5] = 70

In [17]:
print(a[0,:])    #mistake: missed comma

[1 2 3 4 5 6 7 8]


## Zeros/Ones method in NumPy

In [60]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [64]:
np.full((4,4),50)

array([[50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50],
       [50, 50, 50, 50]])

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.full((2,4),20)

array([[20, 20, 20, 20],
       [20, 20, 20, 20]])

In [22]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [23]:
print(a)

[[ 1  2  3  4  5  6]
 [10 20 30 40 50 60]
 [12 12 12 12 12 12]
 [11 21 31 41 51 61]
 [13 24 34 44 54 64]]


In [43]:
#Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?
a[ :3,-5:] #<-- Rows: Start from index 0 and go up to, but not including, index 3.
           #   Columns : Start from -5 index and continue until end
# Rows : 0-2
# Columns: -5-end


array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

In [28]:
a[4,:3]

array([13, 24, 34])

In [31]:
a[0:3,1:]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

**Question #2**
Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

In [61]:
n = int(input("Enter your number: "))

Enter your number: 5


In [69]:
a = np.zeros((n,n),dtype='int')

In [70]:
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [71]:
a[n//2,:]=1 #Row
a[:,n//2]=1.   #Column
print(a)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


### **Arithmetic Operations with NumPy - Maths + Stats**

In [73]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [79]:
a//2

array([0, 1, 1, 2])

In [80]:
print(a)

[1 2 3 4]


In [90]:
print(np.min(a))

1


In [92]:
print(a.max())

4


In [85]:
print(np.max(a))

4


In [94]:
print(np.mean(a))

2.5


In [95]:
print(np.sum(a))

10


In [104]:
b = np.array([[1,2,3,4],[50,60,70,80],[10,20,30,40],])
print(b)

[[ 1  2  3  4]
 [50 60 70 80]
 [10 20 30 40]]


In [105]:
np.max(b,axis=0) #axis=0 → columns survive
                 #axis=1 → rows survive

array([50, 60, 70, 80])

In [106]:
np.max(b,axis=1)

array([ 4, 80, 40])

In [107]:
np.min(b,axis=0)

array([1, 2, 3, 4])

In [108]:
np.min(b,axis=1)

array([ 1, 50, 10])

In [112]:
np.sum(b,axis=0) #Sum vertically → one result for each column.

array([ 61,  82, 103, 124])

In [114]:
np.sum(b,axis=1) #Sum horizontally ->one result for each row

array([ 10, 260, 100])